version: "3.8"

services:
  c-conn-watcher:
    image: c-conn-watcher
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - CCONN_WATCHER_INTERVAL=5
      - CCONN_WATCHER_DB_URL=postgres://temba:temba@localhost/temba?sslmode=disable&Timezone=UTC
      - CCONN_WATCHER_CHANNELS=1, 2, 3
      - CCONN_WATCHER_PORT=8080
    network_mode: "host"
    depends_on:
      - prometheus
      - grafana
    
  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    network_mode: "host"
  grafana:
    image: grafana/grafana:7.1.5
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    network_mode: "host"
volumes:
  prometheus_data: {}